blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/aytordev/system/discussions/new?category=q-a
    about: Ask a question about this project
  - name: Request a feature
    url: https://github.com/aytordev/system/discussions/new?category=ideas
    about: Share ideas for new features
